service: files-service

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: tesseract-admin

plugins:
  # temp fix to hot reload issue (see https://github.com/dherault/serverless-offline/issues/864)
  # is --useChildProcesses flag (see package.json) 
  - serverless-plugin-typescript
  - serverless-offline
functions:
  fileResponse:
    handler: src/index.fileResponse
    events:
      - cloudFront:
          eventType: origin-response
          origin: s3://tesseract-files.s3.amazonaws.com/
  fileAuth:
    handler: src/index.fileAuth
    events:
      - cloudFront:
          eventType: viewer-request
          origin: s3://tesseract-files.s3.amazonaws.com/
          # origin: 
          #   DomainName: s3://tesseract-files.s3.amazonaws.com/
          #   S3OriginConfig:
          #     cloudfrontAuth: ''
          behavior:
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
              - 'PUT'
              - 'PATCH'
              - 'POST'
              - 'DELETE'
            CachedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
